accum_grad: 1
adam_betas: (0.9, 0.999)
adam_eps: 1.0e-08
add_eos: false
cat_sent: false
d_inner_hid: 2048
d_k: 64
d_model: 512
d_v: 64
data_workers: 8
descend_steps: 300000
dropout: 0.3
eval_max_tok: 40000
fp16: false
fp16_opt_level: O1
gpus: 1
load_checkpoint: null
lr: 0.0001
lr_schedule: fixed
max_len: 40
max_steps: 500000
max_tok: 10000
model_type: blm
multigpu: false
n_head: 8
n_layers: 6
n_mc: 1
root_dir: checkpoints/unlabelled25/pos/blm/
seed: 1111
share_emb_prj_weight: true
train: data/unlabelled25/train.txt
val_check_interval: 0
valid: data/unlabelled25/valid.txt
vocab_size: 27
warmup_steps: 4000
weight_decay: 1.0e-05
